### ISSUE TITLE
vsco-dl  JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by estatistics** [tecome/vsco-dl#2]
> vsco-dl -ij emblanjerve
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 514, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 386, in decode
>     obj, end = self.raw_decode(s)
>                ^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 416, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/elias/.local/bin/vsco-dl", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/elias/.local/lib/python3.12/site-packages/vscodl/vscodl.py", line 269, in main
>     scraper.download_images()
>   File "/home/elias/.local/lib/python3.12/site-packages/vscodl/vscodl.py", line 160, in download_images
>     self.get_site_id()
>   File "/home/elias/.local/lib/python3.12/site-packages/vscodl/vscodl.py", line 77, in get_site_id
>     info = vsco.get_sites(self.session, self.uid, self.username)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/elias/.local/lib/python3.12/site-packages/vscodl/vsco.py", line 15, in get_sites
>     return session.get(constants.VSCO_URL + "/ajxp/{}/2.0/sites?subdomain={}".format(uid, username)).json()["sites"]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by fafoulon** [comment]
Hi, i have the same error
